baseURL = "https://coredumped.dev"
languageCode = "en-us"
title = "Core Dumped"
theme = "hyde-y"
metaDataFormat = "yaml"
copyright = "(c) 2021 Troy Hinckley."

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[params]
        description = "A core dump of ideas and projects"
        author = "Troy Hinckley"
        sidebar = "left"
        home = "home"
        topline = "A core dump of ideas and projects"

[author]
    name = "Troy Hinckley"
    email = "troy.hinckley@gmail.com"
